# Site settings
title: VeSinFiltro
email: info@vesinfiltro.com
description: > # this means to ignore newlines until "baseurl:"
  VEsinFiltro es un repositorio de información sobre la censura y filtrado de contenidos en Venezuela. Herramientas para denucniar y evaduar bloqueos y más
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://vesinfiltro.com" # the base hostname & protocol for your site
twitter_username: vesinfiltro

navigation:
- title: Bloqueos
  url: /bloqueos/
- title: reporta
  url: /

# Build settings
markdown: kramdown

collections:
  bloqueos:
    output: true
  documenta:
    output: true
